### ISSUE TITLE
Cash flows prop funds

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#14]
## Goal

We want to add a template for the Statement of Cash Flows (Proprietary Funds) to our Excel sheet. Our goal is to have the full Excel template done by Tuesday's meeting, so please try to push your changes by Monday night. If you can't finish everything, no worries, just push what you have on Monday night.

## Tasks

 - [x] Switch to the branch for this issue:
```
git fetch origin
git checkout 14-cash-flows-prop-funds
```
 - [x] In the excel template, create a new sheet, using the Net Position - Prop Funds as the template. Name the new tab `Prop Fund Cash Flows`
 - [x] Change the header: the statement will be `Statement of Cash Flows`, and the date should be "For the Year Ended" + the date from the `Master Info` tab. (You can copy the formula from B4 on the `Statement of Activities` sheet.
 - [x] Change the section headers to match the bolded headers on Flint's [Statement of Cash Flows](https://xbrlus.github.io/acfr/ixviewer/ix.html?doc=../samples/74/Flint2022.htm#if843ff31c9064415a125a236a2928819_136). 
 - [ ] Create new tab with a look-up table for appropriate labels using the [taxonomy sheet's ](https://docs.google.com/spreadsheets/d/18LhDW7fYq5cQaqxheBgqMBNHYAvxyOfO/edit#gid=2135334119)`Proprietary Funds` tab under the Cash Flows header on row 2173 (700000 - Statement - Proprietary Funds Cash Flows - Type of Activities).
 - [ ] Just like the last look-up table you made, this one will have 3 columns: category, label (with spaces), and the XBRL tag. The categories will match the Flint headers and should have the word "Abstract" in them. (Ex. the first category is "Cash Flows from Operating Activities" and captures all tags from row 2183-2218.)
 - [ ] Create new groups from the lookup table that correspond to each header on the `Prop Fund Cash Flows` tab. Edit the line item drop down menus in column B to pull from the appropriate groups.
 - [ ] Edit the formulas in column A to use the correct lookup table (ie. your new tab).
