### ISSUE TITLE
Net Position Fid Funds

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#15]
## Goal

Add the Statement of Fiduciary Net Position

## Tasks

 - [ ] Create columns with customizable names
 - [ ] Create section headers for: Assets, Liabilities, Deferred Inflow of Resources, Deferred Outflow of Resources, and Net Position. Each section should have space for line items and a line for the total at the bottom of the section.
 - [ ] Create and link an appropriate lookup table
