### ISSUE TITLE
Typed dimensions

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#20]
## Goal
Implement typed dimensions. 

## Tasks
 - [x] Start with allowing typed members for the Fund Identifier Axis for all GovFund sheets. 
 - [x] Test with Clayton sample sheet
 - [ ] Add support for GovFunds Balance Sheet
 - [ ] Add support for Prop Funds

**Comment by kwheelan** [comment]
Review to avoid redundancy in the `process_cells()` functions of `Table` child classes
