### ISSUE TITLE
ACFR final edits

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#24]
## Goal 

Finish the last few pieces of the ACFR template

## Tasks

 - Checkout this branch:
```
git pull
git checkout 24-ACFR-edits
```

### Add additional reconciliation table

We want to create another tab for reconciliation of government funds. You shouldn't have to do much formatting here; they don't have any XBRL tags. 

- [x] Copy the reconciliation template already in the Excel sheet (`Reconciliation Balance Sheet`, which is the 2nd green tab). 
- [x] Take a look at [the Clayton ACFR](https://drive.google.com/drive/folders/1yjTbsMA6CLcHtfqKSfQ2EaEJkSZRLGYF)'s `Reconciliation of Governmental Funds Statement of Revenues, Expenditures and Changes in Fund Balances to the Statement of Activities and Changes in Net Position` (page 47 in the digital PDF).
- [x] Edit the statement and scope at the top of the sheet
- [x] Edit the section headers (the dark gray rows should have labels that match Clayton's all-caps section headers).

### New look-up table

The `GovFund Stmt of Rev Exp and Chg` tab needs a new lookup table with slightly different XBRL tags than we already have.

- [x] Create a new tab for the lookup table (if you want to see the other lookup tables, the tabs are just hidden).
- [x] Like you did before, we want to have a column for the category, a column for the XBRL tag, and a column for the label (without spaces). You can use the XBRL items from the Taxonomy sheet, tab `GovernmentalFunds`, rows under `400000 - Statement - Governmental Funds Revenues, Expenditures and Changes in Fund Balances, Other Funds` (so rows 1636-2041)
- [x] Like before, the categories will match the "abstract" item above it.

### Edit the `GovFund Stmt of Rev Exp and Chg` tab

- [x] Now you can edit the drop-downs in the `GovFund Stmt of Rev Exp and Chg` to pull from your new lookup table

Let me know if you have any questions!
