### ISSUE TITLE
Improve loading wheel

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#25]
## Goal

Make the website look more professional

## Tasks

 - [ ] Make the loading wheel look better
 - [ ] Center it, and make it appear on top of the webpage (which should be made opaque)
 - [ ] If possible, add text detailing the steps: uploading, processing, validating, creating viewer

**Comment by lucakato** [comment]
@kwheelan hi, I centered the wheel for now. Could you clarify what you mean by this part? `make it appear on top of the webpage (which should be covered by the wheel or made opaque)`
https://github.com/closup/process-xbrl/assets/55814205/34e75d6f-c00e-4dc6-a4c4-a0e42492fed4
Thanks

**Comment by kwheelan** [comment]
That looks great! I just meant to have the wheel appear overlapping the content (as you've done). When you have a chance, could you also just confirm that the wheel acts as expected when you upload 2 excel files or 0 excel files? Both should give an error, and the wheel should disappear after you dismiss the dialog box.

**Comment by lucakato** [comment]
@kwheelan Yup the wheel acts as expected for those 2 cases. 

I'm gonna see if I can add text detailing those steps. My thought is it only takes like 3s for the XBRL to complete (at least with Clayton ex) so I'm not sure if it makes sense to display each word 'uploading, processing, validating, creating viewer' within that time frame (I'm assuming your idea is displaying the word sequentially).

Maybe something like a simple progress bar might look better? Or a spinning wheel which acts a progress bar?

**Comment by kwheelan** [comment]
It's a lot slower when we add the Word documents or a longer excel sheet (it's the XBRL validation that takes the longest time). I also think there's some caching, so it takes longer with a document it hasn't seen before.

That being said, feel free to go for a progress bar/wheel instead of the words. Up to you

**Comment by lucakato** [comment]
I see. Is there an example of a longer excel sheet I can test it with?

**Comment by kwheelan** [comment]
I don't have an Excel sheet on hand, but try uploading the Excel sheet you have as well as the attached Word doc. For me, it takes ~20 seconds.
[CA Clayton 2022 Notes (with comments).docx](https://github.com/closup/process-xbrl/files/15049649/CA.Clayton.2022.Notes.with.comments.docx)
