### ISSUE TITLE
Template fixes

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#36]
## Goal

Marc took a look at the template and gave us a few more edits. Fixing these should let us use the template for Clayton's ACFR.

## Tasks

 - [x] Check out this branch
```
git fetch
git checkout 36-femplate-fixes
```
 - [x] Can you confirm if you get any warnings when you open the document about either circular references or external links? If you see either, I can help you debug those.
 - [x] Will you format all the $ values in the sheets as integers – no decimal places (this is for the yellow cells where the user will input data and also for the gray cells that auto-populate).
 - [x] *Left* justify the dates for each sheet (usually cell B4) (edited)
 - [x] Can you alphabetize the `Lookup GovFund Stmt Rev Exp Ch` within each category? (Basically, we want the drop-down menus in the `GovFund Stmt Rev Exp Ch` to be alphabetical).
 - [x] For each table, will you look at the corresponding lookup table and delete any rows that include tags we already hard-coded into the sheet. For example, `GovFund Stmt Rev Exp Ch` has tag `acfr:RevenuesModifiedAccrual` in cell A23, so we would want to delete row 160 from the `Lookup GovFund Stmt Rev Exp Ch` table.

**Comment by joffemd** [comment]
We actually want to left justify the dates in cell B4 so that they line up under the three lines of text above.
