### ISSUE TITLE
Net Position Prop Funds

### ISSUE THREAD

**Issue by kwheelan** [closup/process-xbrl#9]
## Goal
 We want to add the Statement of Net Position (Proprietary Funds) table to our Excel ACFR template.

## Background 

This financial table is similar to the government-wide statement of net position (already formatted in our template in the "Statement of Net Position" tab), but it zooms in on just the "business-type" activities in the municipality. This might include entities like the water utility or the municipal swimming pool. 

Municipalities also report their "internal service funds," which are proprietary funds within the government that provides goods/services for different part of the government. For instance, a city might use an internal service fund to run a print shop that produces documents for all its departments, which pay for printing services as they use them.

## Tasks

 - [x] Take a look through the ACFRs in this [shared folder](https://drive.google.com/drive/folders/1yjTbsMA6CLcHtfqKSfQ2EaEJkSZRLGYF) or any others you want to find online. Look at the Statement of Net Position (Proprietary Funds) table in the ACFRS to get a sense of the general format.
 - [x] clone the repository to your local and checkout the branch associated with this issue:
 ```
git clone https://github.com/closup/process-xbrl
git checkout 9-net-position-prop-funds
```

 - [x] The Excel sheet is in `static/input_files/ACFR_template.xlsx`
 - [x] You can add a new tab called `Statement of Net Position - Prop Funds` and use the existing Statement of Net Position tab as a template
 - [ ] You'll just need to edit the column names to be customizable under a "Business-type Activities - Enterprise Funds" header (plus a total column) and then a column for "Internal Service Fund" under a governmental activities header. Take a look at a few different ACFRs to get a sense of how many columns you'll need.
 - [ ] Add conditional formatting to make the total column disappear if only one fund name is filled under the Business-type Activities header. (This is a little tricky, but you can look at "Statement of Activities" as an example and see what happens when you delete the text in cell E6).

Feel free to send me a Slack message or comment here if anything is unclear!
